### ISSUE TITLE
a good paper

### ISSUE THREAD

**Issue by 1bing2** [h-waldschmidt/transductive-experimental-design#3]
I will recommend you a good paper,it may help your research

Q. Sun, C. Bai, H. Geng, and B. Yu, “Deep Neural Network Hardware Deployment Optimization via Advanced Active Learning,”
in IEEE/ACM Proceedings Design, Automation and Test in Eurpoe (DATE), 2019.

**Comment by h-waldschmidt** [comment]
Thank you!
I will definitely look into it.

Do you also have other recommendations for machine learning resources (I'm fairly new to the field)?

**Comment by 1bing2** [comment]
> Thank you! I will definitely look into it.
> 
> Do you also have other recommendations for machine learning resources (I'm fairly new to the field)?

I'm new too.Maybe we can help each other?

**Comment by 1bing2** [comment]
> > Thank you! I will definitely look into it.
> > Do you also have other recommendations for machine learning resources (I'm fairly new to the field)?
> 
> I'm new too.Maybe we can help each other?

my email:   bingli226@mail.ustc.edu,cn

**Comment by h-waldschmidt** [comment]
Sure!
I will hit you up if I have any questions.
If you have any questions for me you can reach me at: [st171805@stud.uni-stuttgart.de](st171805@stud.uni-stuttgart.de)
